services:
  app:
    build: .
    env_file:
      - .env
    links:
      - redis
    ports:
      - "8080:8080"
    volumes:
      - /public
      - ./:/app
      - /app/node_modules
  redis:
    image: redis

  nginx-proxy:
    image: quay.io/ukhomeofficedigital/nginx-proxy-govuk
    environment:
      - PROXY_SERVICE_HOST=app
      - PROXY_SERVICE_PORT=8080
      - NAXSI_USE_DEFAULT_RULES=FALSE
      - CLIENT_MAX_BODY_SIZE=200
      - ADD_NGINX_SERVER_CFG=add_header Cache-Control private;add_header X-Frame-Options "SAMEORIGIN" always;add_header X-Content-Type-Options "nosniff" always;add_header X-XSS-Protection "1; mode=block" always;location /public {add_header Cache-Control max-age=86400;add_header X-Frame-Options "SAMEORIGIN" always;add_header X-Content-Type-Options "nosniff" always;add_header X-XSS-Protection "1; mode=block" always;alias /public;}
      - ERROR_REDIRECT_CODES=599
    ports:
      - "443:10443"
      - "80:10080"
    links:
      - app
    volumes_from:
      - app
